name: drobnitsa-test
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./p-seed:/var/www/html
      - ./nginx-cnf:/etc/nginx/conf.d
      - ./nginx.logs:/var/log/nginx/
  php:
    image: php:7.2-fpm
    volumes:
      - ./p-seed:/var/www/html
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: labbit
      MYSQL_ROOT_PASSWORD: rootlabbit
      MYSQL_USER: labbit
      MYSQL_PASSWORD: labbit
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
  redis:
    image: redis:latest